services:
  build-uboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: armbian-build-uboot
    privileged: true
    network_mode: host
    volumes:
      - .:/workspace
      - armbian-cache:/workspace/cache
      - /dev:/dev
    environment:
      - FORCE_CHECKOUT=no
      # - REMOTE_HOST=192.168.128.15
      # - SKIP_BUILD=1

volumes:
  armbian-cache: