name: Build PBSTVStick Image

on:
  workflow_dispatch:
  push:
    branches:
      - build
    paths:
      - 'config/boards/pbstvstick.csc'
      - 'userpatches/**'
      - '.github/workflows/build-pbstvstick.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Inject private credentials into customize-image.sh
        run: |
          sed -i "s/REPLACE_WITH_SSID/${{ secrets.WIFI_SSID }}/g" userpatches/customize-image.sh
          sed -i "s/REPLACE_WITH_KEY/${{ secrets.WIFI_KEY }}/g" userpatches/customize-image.sh
          sed -i "s/REPLACE_WITH_ROOT_PW/${{ secrets.ROOT_PASSWORD }}/g" userpatches/customize-image.sh

      - name: Build Armbian Image
        run: |
          sudo ./compile.sh build \
            BOARD=pbstvstick \
            BRANCH=current \
            BUILD_DESKTOP=no \
            BUILD_MINIMAL=no \
            KERNEL_BTF=no \
            KERNEL_CONFIGURE=no \
            RELEASE=bookworm \
            CLEAN_LEVEL=make,cache,sources

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: armbian-pbstvstick-bookworm
          path: output/images/*
          retention-days: 7
