name: Build PBSTVStick Image

on:
  workflow_dispatch:
  push:
    branches:
      - build
    paths:
      - 'config/boards/pbstvstick.csc'
      - 'patch/kernel/archive/sunxi-6.18/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Inject private credentials into customize-image.sh
        run: |
          sed -i "s/REPLACE_WITH_SSID/${{ secrets.WIFI_SSID }}/g" userpatches/customize-image.sh
          sed -i "s/REPLACE_WITH_KEY/${{ secrets.WIFI_KEY }}/g" userpatches/customize-image.sh
          sed -i "s/REPLACE_WITH_ROOT_PW/${{ secrets.ROOT_PASSWORD }}/g" userpatches/customize-image.sh

      - name: Cache Compiler Objects (ccache)
        uses: actions/cache@v6
        with:
          path: .ccache
          key: ${{ runner.os }}-armbian-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-armbian-ccache-

      - name: Build Armbian Image
        run: |
          sudo ./compile.sh build \
            BOARD=pbstvstick \
            BRANCH=current \
            BUILD_DESKTOP=no \
            BUILD_MINIMAL=no \
            KERNEL_BTF=no \
            KERNEL_CONFIGURE=no \
            RELEASE=bookworm \
            KERNEL_GIT=shallow

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: armbian-pbstvstick-bookworm
          path: output/images/*
          retention-days: 7
